LT-2622: Update underlying mds code
lykkecloud/MarginTrading.AssetService pull request #107
Opened 2020-10-21 09:25 UTC by gponomarev-lykke

2020-10-21 10:04 UTC, tarurar commented on src/MarginTrading.AssetService.Services/ProductsService.cs
> +                    await _addOrUpdateValidation.ValidateAllAsync(product, username, correlationId, existing.Value);
Checked the validations code and it looks like there are no validations that would require `existing.Value`, except the only method called `SetExistingFields` which doesn't seem like a validation method ). probably, it is not a validation but an update.

2020-10-21 10:04 UTC, tarurar commented on src/MarginTrading.AssetService.Services/RabbitMq/Handlers/UnderlyingChangedHandler.cs
> +                                new Exception($"Cannot update a product with underlying mds code {e.OldValue.MdsCode}: {productUpdateResult.Error.ToString()}"));
Why do you need exception object here?

2020-10-21 10:10 UTC, gponomarev-lykke commented on src/MarginTrading.AssetService.Services/ProductsService.cs
> +                    await _addOrUpdateValidation.ValidateAllAsync(product, username, correlationId, existing.Value);
I will probably rename the validation class in the clean up task. It validates existing fields and updates the missing ones. Most of the validations should be unnessesary at this point, but I left them for some additional safety.

2020-10-21 10:14 UTC, gponomarev-lykke commented on src/MarginTrading.AssetService.Services/RabbitMq/Handlers/UnderlyingChangedHandler.cs
> +                                new Exception($"Cannot update a product with underlying mds code {e.OldValue.MdsCode}: {productUpdateResult.Error.ToString()}"));
WriteError only have a variant with an exception as an input parameter.

I think that the case when product is not found can be valid e.g. if a specific broker does not use this specific product. So I used warning for that case. 

But if product exists, and we fail to update it, it means we will leave the system in an inconsistent state - the underlying will be updated and the product will be not. So we have to nofity users somehow.

2020-10-21 10:14 UTC, gponomarev-lykke commented on src/MarginTrading.AssetService.Services/ProductsService.cs
> +                var contract = _convertService.Convert<Product, ProductContract>(existing.Value);
Yes, it is a bit better I guess. I'll fix it

2020-10-21 10:23 UTC, gponomarev-lykke commented on src/MarginTrading.AssetService.Services/ProductsService.cs
> +                var contract = _convertService.Convert<Product, ProductContract>(existing.Value);
We discussed it with Iliyan and decided to use  this approach
`var product = existing.Value.ShallowCopy();`
Since FreezeInfo is not updated in this method, it should work fine

2020-10-21 13:16 UTC, tarurar commented on src/MarginTrading.AssetService.Services/RabbitMq/Handlers/UnderlyingChangedHandler.cs
> +                                new Exception($"Cannot update a product with underlying mds code {e.OldValue.MdsCode}: {productUpdateResult.Error.ToString()}"));
Exception object is not mandatory there. You can just pass `null`.

2020-10-21 13:16 UTC, tarurar approved these changes

2020-10-21 18:06 UTC, andrey-anokhin requested changes

2020-10-21 18:06 UTC, andrey-anokhin commented on src/MarginTrading.AssetService.Services/ProductsService.cs
> +                var validationResult =
We agreed to remove this validation

2020-10-21 18:06 UTC, andrey-anokhin commented on src/MarginTrading.AssetService.Services/RabbitMq/Handlers/UnderlyingChangedHandler.cs
> +                                new Exception($"Cannot update a product with underlying mds code {e.OldValue.MdsCode}: {productUpdateResult.Error.ToString()}"));
We agreed to throw an exception, so we can keep it, but it should be thrown.

2020-10-23 15:45 UTC, andrey-anokhin approved these changes

2020-10-26 14:13 UTC, merged