LT-2717: Start product from various sources
lykkecloud/MarginTrading.AssetService pull request #115
Opened 2020-10-28 14:18 UTC by gponomarev-lykke

2020-10-28 15:36 UTC, tarurar approved these changes

2020-10-30 08:05 UTC, andrey-anokhin requested changes

2020-10-30 08:05 UTC, andrey-anokhin commented on src/MarginTrading.AssetService/Workflow/Products/StartProductsSaga.cs
> +                var endOfNextDay = DateTime.UtcNow.Date.AddDays(2);
DateTime.UtcNow is not correct here. We may finish EOD after midnight, meaning that AddDays(2) will be the wrong date. Looks like we should add TradingDate to EodProcessFinishedEvent and use it here.

2020-11-20 07:51 UTC, tarurar approved these changes

2020-11-20 07:54 UTC, merged