Lt 2748 halfworkingday feature
lykkecloud/MarginTrading.AssetService pull request #150
Opened 2021-01-25 10:45 UTC by tarurar

2021-01-26 05:20 UTC, andrey-anokhin requested changes

2021-01-26 05:20 UTC, andrey-anokhin commented on src/MarginTrading.AssetService.Services/Extensions/MarketScheduleExtensions.cs
> +                DayOfWeek = DayOfWeek.Saturday
This is also my mistake (it was not merged to master for some reason) but in the previous sprint we made this configurable.

2021-01-26 05:20 UTC, andrey-anokhin commented on src/MarginTrading.AssetService.SqlRepositories/Migrations/20210112161318_HalfWorkingDayFeature.cs
> +                "20210112191618_ConvertSchedule.sql");
Where is 20210112191618_ConvertSchedule.sql?

2021-01-28 07:21 UTC, tarurar commented on src/MarginTrading.AssetService.Contracts/MarketSettings/MarketScheduleContract.cs
> +    public class MarketScheduleContract
The plan is to move into this model Open and Close hours, Timezone, Holiday. Just didn't want to introduce contract breaking changes with functional changes. Let the functional changes be properly tested and delivered, once it is done we'll make the contract update. It is much easier than crossing it with functional updates.

2021-01-28 07:23 UTC, tarurar commented on src/MarginTrading.AssetService.Contracts/MarketSettings/MarketSettingsContract.cs
> +        public TimeSpan[] Open { get; set; }
We keep backward compatibility on gateways level, everywhere we depend on front and mobile. I think internally we are in full control of contracts, that is why a lot of services were updated with new nuget package versions.

2021-01-28 07:38 UTC, tarurar commented on src/MarginTrading.AssetService.Services/Extensions/CronutAssetExtensions.cs
> +            asset.Underlying.MarketDetails.MarketHours.Open = marketScheduleUtcRespectful.Open;
`Cronut.Dto` has also been updated to support multi-sessions. As soon as I am aware of `Asset` model is not used on front-end side so we can safely update it as soon as we guarantee internal compatibility.

2021-01-28 07:52 UTC, tarurar commented on src/MarginTrading.AssetService.Services/Extensions/MarketScheduleExtensions.cs
> +                $"{marketId}_working_hours_open{open}_close{close}",
There is no mistake. `GetSingleSessionScheduleSettings` supports previous case with single session per day whereas `GetMarketHoursScheduleSettings` supports multi-sessions and my assumption is that for testing new multi-session feature it will be much easier for QAs to know when the market is down. The name is `$"{marketId}_none_working_hours_open{sessionClose}_close{nextSessionOpen}"` and for single session name is `$"{marketId}_working_hours_open{open}_close{close}"`. Note open and close rotation.

2021-01-28 07:53 UTC, tarurar commented on src/MarginTrading.AssetService.SqlRepositories/Migrations/20210112161318_HalfWorkingDayFeature.cs
> +                "20210112191618_ConvertSchedule.sql");
Added.

2021-01-28 10:24 UTC, tarurar commented on src/MarginTrading.AssetService.Services/Extensions/MarketScheduleExtensions.cs
> +                DayOfWeek = DayOfWeek.Saturday
Merged in master updates.

2021-01-28 10:40 UTC, andrey-anokhin approved these changes

2021-01-28 10:40 UTC, merged